### ISSUE TITLE
readsf~ is not supported in a multi-instance/thread context

### ISSUE THREAD

**Issue by tlongshaw** [pierreguillot/Camomile#218] opened 2020-11-28 12:44 UTC
Hi, I'm building the framework of a sampled piano for part of a university project and I'm having trouble getting logic to validate the plugin. 

I've noticed this issue only occurs when I try to use the readsf~ object to read the remainder of a sample (the first second is stored in a table), though the patch itself works fine in Pd. 

OS Catalina 10.15.7
Logic 10.6

Thanks.

**Comment by pierreguillot** [comment] 2020-12-03 08:11
This might be related to notarization... I will investigate.

**Comment by tlongshaw** [comment] 2020-12-03 15:06
Great thanks. I've since noticed the same problem with VST3 files in Reaper and had no luck getting any project with the readsf~ object to work without crashing. (Incase you don't have access to logic)

**Comment by pierreguillot** [comment] 2020-12-15 19:32
In fact, this could be related to this Pd issue https://github.com/pure-data/pure-data/issues/1225. I'll update Pd and see if it fixes the bug.

**Comment by pierreguillot** [comment] 2021-01-04 16:25
I managed to reproduce the bug I'll try to find a solution.

**Comment by pierreguillot** [comment] 2021-01-04 16:38
I tested with Pd 0.51-4 it the problem seems to be fixed.

**Comment by tlongshaw** [comment] 2021-01-04 20:22
Great thanks, will give this a try... I'm struggling to find a download for Pd 0.51-4 - where could I find this?

**Comment by pierreguillot** [comment] 2021-01-05 15:52
While waiting for the new version, you must compile the plugins yourself with the most recent version of Pd. In case you don't know how to compile, here is a pre-built version but I didn't really test it. 
[Camomile-macOsX.zip](https://github.com/pierreguillot/Camomile/files/5771189/Archive.zip)

**Comment by tlongshaw** [comment] 2021-01-07 21:08
I've tried this across a few projects and it seems to be working well. Thanks!

**Comment by pierreguillot** [comment] 2021-01-11 21:59
This is fixed on dev/v1.0.8 and there is a [beta version](https://github.com/pierreguillot/Camomile/releases).

**Closed as completed by pierreguillot** 2021-01-11 21:59 UTC
Labels: bug
