### ISSUE TITLE
textfile / text define : reading attempt of non-existing file makes plugin crash

### ISSUE THREAD

**Issue by jyg** [pierreguillot/Camomile#239] opened 2021-02-05 14:34 UTC
1. when sending a message [read ...( to [textfile] or [text define ...], plugin crashes if the specified file doesn't exist. 
      
2. tested on linux 18.04-5 LTS  with latest reaper 64 and camomille vst3   v1.0.8 beta
     (using   PdStalFx plugin to load the patch)
       
3. Open the attached  patch.
[test_textfile.pd.zip](https://github.com/pierreguillot/Camomile/files/5933124/test_textfile.pd.zip)

if you click on the second row of bngs, you load the existing test_textfile.pd into [textfile] and [text define] objects
if you click on the first row, you are trying to load an unexisting file and the plugin crashes
![image](https://user-images.githubusercontent.com/1431894/107047390-0f22ef80-67c8-11eb-92fb-42f4c7bea83c.png)

**Comment by pierreguillot** [comment] 2021-02-06 12:12
I can reproduce the bug on Linux (not MacOS and I didn't test on Windows yet). The problem also occurs using Ardour.

**Comment by jyg** [comment] 2021-02-08 16:42
Here is an abstraction to insert before [textfile] / [text define] inlet in order to prevent crash.
![image](https://user-images.githubusercontent.com/1431894/107251804-071bb780-6a35-11eb-872a-b434b3295bbe.png)
[#239-workaround.pd.zip](https://github.com/pierreguillot/Camomile/files/5945181/239-workaround.pd.zip)

**Comment by pierreguillot** [comment] 2021-02-08 18:27
It seems that this [call of error()](https://github.com/pure-data/pure-data/blob/eeef4ba9130d3182146927c37fa57d61bbff0f0b/src/m_binbuf.c#L878) generates a crash. The only way I managed to fix the problem is to remove this line. I couldn't find the exact cause of the crash so far, I tried to remove all the content of the error() function so the function doesn't do anything but it still crashes. It seems that the address of the function is not valid...

**Comment by pierreguillot** [comment] 2021-02-08 18:30
Perhaps it gets confused with this [function](https://man7.org/linux/man-pages/man3/error.3.html)?

**Comment by jyg** [comment] 2021-02-09 09:36
> It seems that this [call of error()](https://github.com/pure-data/pure-data/blob/eeef4ba9130d3182146927c37fa57d61bbff0f0b/src/m_binbuf.c#L878) generates a crash. 

Yes, and indeed soundfiler_read uses pd_error() instead of error() and doesn't crash.

> Perhaps it gets confused with this function?

You mean it should be linked instead with 
`EXTERN void error(const char *fmt, ...) ATTRIBUTE_FORMAT_PRINTF(1, 2);` as defined in m_pd.h ?

**Comment by pierreguillot** [comment] 2021-02-09 09:43
> You mean it should be linked instead with
> `EXTERN void error(const char *fmt, ...) ATTRIBUTE_FORMAT_PRINTF(1, 2);` as defined in m_pd.h ?

Yes, this is my assumption. But for an obscure reason, it links with another function named error()...

**Comment by jyg** [comment] 2021-02-09 09:59
It shoud be related to Juce framework ?
Another potential crasher : g_clone.c that contains an `error()` call.
Put `[clone print 4]` in a patch and it generates the error `clone: can't clone 'print' because it's not an abstraction`  . This crashes the plugin.

**Comment by pierreguillot** [comment] 2021-02-09 10:12
> It shoud be related to Juce framework ?

I don't think but I'm not sure. I sent a [mail](https://lists.puredata.info/pipermail/pd-dev/2021-02/022665.html) on the pd-dev list to get some help from libpd and linux gurus

> Another potential crasher : g_clone.c that contains an error() call.

In fact, all the uses of the `error()` function cause a crash. And the function is used many times... :(

**Comment by pierreguillot** [comment] 2021-02-17 11:19
I did a dirty hack but can you confirm that the bug is fixed with these [binaries](https://github.com/pierreguillot/Camomile/suites/2058185848/artifacts/41519774)?

**Comment by jyg** [comment] 2021-02-17 14:00
I cannot open the link.

> I did a dirty hack but can you confirm that the bug is fixed with these [binaries](https://github.com/pierreguillot/Camomile/suites/2058185848/artifacts/41519774)?

**Comment by jyg** [comment] 2021-02-17 14:07
yes it works ! Thanks

**Comment by pierreguillot** [comment] 2021-02-21 17:00
@jyg I found a good fix. Can you test the Linux artifacts of this [commit](https://github.com/pierreguillot/Camomile/actions/runs/586798502)? Thank you!

**Comment by jyg** [comment] 2021-02-22 19:45
I tested camomile.so and camomileFx.so . It works perfectly, doesn't crash anymore. Thanks !

**Closed as completed** 2021-02-22 21:50 UTC
Labels: bug, linux
