### ISSUE TITLE
CamomileFX shows up as a Software Instrument in Logic Pro X 10.3.2

### ISSUE THREAD

**Issue by njaardyboi** [pierreguillot/Camomile#115] opened 2018-05-28 14:35 UTC
It still works if I sidechain the audiosignal I want to use through the "CamomileFX" software instrument, which is a big problem since this makes it impossible to use them in real time which as a guitarist is pretty important. I specified all the midioptions in the text file as an attempted fix. It also does not show the name of each individual plugin, even though they work.
I know I've installed them properly following the guide. Is this normal behavior for Camomile plugins?

<img width="631" alt="skjermbilde 2018-05-28 kl 16 29 42" src="https://user-images.githubusercontent.com/39702991/40619241-9a95d4a6-6294-11e8-8ebf-09bdd472134d.png">

Here you see CamomileFX show up as a Software Instrument.

<img width="684" alt="skjermbilde 2018-05-28 kl 16 29 56" src="https://user-images.githubusercontent.com/39702991/40619244-9d01579c-6294-11e8-8fc1-b55fb497e170.png">

In the software instrument menu the effects show up – but without their names.

<img width="215" alt="skjermbilde 2018-05-28 kl 16 30 50" src="https://user-images.githubusercontent.com/39702991/40619243-9bc533e4-6294-11e8-8018-03059763b912.png">

The CamomileFX plugins do not show up in the effect list at all.

As a sidenote I was wondering wether the problem was the .component format, so I tried loading plugins in Audacity in stead, and at first it looked good. Plugins showed up in the list with the right names etc. but when I tried to open them Audacity crashed, regardless of wether I used 1.0.4 or 1.0.5 versions of plugins.

And furthermore: I know from previous issues that you do not have the chance to test Logic thoroughly, so I was mostly wondering wether this was a quirk of logic or a quirk of the plugin itself.

EDIT: tested it as a .VST in FL Studio 20 and none of the previous problems showed up, seems to be unique to Audacity and Logic.

**Comment by pierreguillot** [comment] 2018-05-29 08:56
Thanks for the report.

Yes, that's strange.
Can you send me the binary of one of your plugin (YourPlugin.component) ? This way I could check if everything is well defined. 

Audacity has a really bad plugin support so I'm not surprised but when I tried it worked well... can you tell me which version of Audacity you use and if you tried with the VST2 / VST3 or the Audio Unit ?

And I know that some people use the plugin with Logic, you can try to contact them via the pre-existing issue, the pd-list, the pd forum, facebook or whatever.

**Comment by njaardyboi** [comment] 2018-05-29 11:18
I'm pretty busy until thursday, but I'll get it done then.

**Comment by pierreguillot** [comment] 2018-06-12 09:38
Any news?

**Comment by pierreguillot** [comment] 2018-06-19 12:45
I close this due to lack of activity, feel free to reopen if needed.

**Comment by aronco206** [comment] 2019-02-04 00:46
Hello, I figured out something related to this, as I'm having the exact same issue.
In the .plist file, key "type" is defined as "aumf". Aumf is Apple's midi-controlled music effect. The correct type for a music effect would be "aufx". See this link for more info: https://developer.apple.com/library/archive/documentation/General/Conceptual/ExtensibilityPG/AudioUnit.html#//apple_ref/doc/uid/TP40014214-CH22-SW1

Unfortunately, simply editing the .plist file, then generating the plugin does not solve the issue. When the .plist file is edited to reflect this change and the plugin is generated, the following is reported on the AU Verification Report:
![screen shot 2019-02-03 at 7 43 22 pm](https://user-images.githubusercontent.com/37984996/52185289-1b949c00-27ec-11e9-9956-9aff13528547.png)

While the report is saying that the correct type is "aumf", its reading this because there's a Music Device MIDI Event somewhere that is causing it to think it should be an aumf when in fact it should be an aufx.

I've been trying to fix it myself but have gotten stuck at this point. I'm hoping @pierreguillot can help here! Let me know if I need to explain anything more clearly. Thank you so much.

**Comment by pierreguillot** [comment] 2019-02-04 19:41
@aronco206 Thanks for your report. Can you share an example (patchs/camomile file/etc.) ? This way I could try to reproduce the bug. Can you confirm that this bug is on Logic specific to AU ? And you don't have same problem with another DAW such as Reaper for example ? 

And Camomile plugin can be of two kinds: effect or instrument and in practice, a Camomile plugin always accepts and/or generates MIDI events and always process and/or generates Audio (but you can enable or disable the MIDI and/or Audio support with Pd) so I guess the right types are:
- instrument: kAudioUnitType_MusicDevice (Instrument variant) - **aumu**
- effect: kAudioUnitType_MusicEffect (Music Effect variant) - **aumf**
using **aufx** would simply disable the MIDI support.

**Comment by pierreguillot** [comment] 2019-02-04 19:49
And can you try to enable the MIDI support in the effect plugin using `midiin true` and/or  `midiin false` (even if it is useless for the plugin) ?

**Comment by aronco206** [comment] 2019-02-04 23:44
Sure, here's the .component I've been trying.
[Glitch.component.zip](https://github.com/pierreguillot/Camomile/files/2830207/Glitch.component.zip)
I tried enabling and disabling midiin, and neither changed anything. I can confirm this is only a Logic glitch, as this isn't a problem even in GarageBand, which is very strange.

I'm noticing something else that might be important. In the plugin list, this audio unit appears as a "MIDI-controlled effect", rather than an "effect". All the other audio unit plugins in Logic appear as "effect". I believe that it is because of this, Logic misidentifies the plugin and places it in the wrong category, making it impossible for it to be used as an audio plugin.

![screen shot 2019-02-04 at 6 23 39 pm](https://user-images.githubusercontent.com/37984996/52244704-d3897e00-28ac-11e9-8be2-5b756a79ea0c.png)


I understand what you're saying about aufx disabling MIDI support, however, I believe this may be the only way to use it as an audio effect in Logic.

I know you can't test on Logic, so please let me know what I can do to help! I love what you've created and I'd really like to get this issue solved. Thanks again.

**Comment by pierreguillot** [comment] 2020-08-07 10:12
This should be fixed on dev/imp-compilation and soon on dev/v1.0.7.

**Closed by pierreguillot** 2020-08-07 10:12 UTC
Labels: bug, help wanted
