### ISSUE TITLE
Linux LV2: Meta parameters don't function via generic interface, at start

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#202] opened 2020-09-04 15:31 UTC
2. **Describe your environment**
Debian Buster, stable
Carla 2.2.0-RC1
Ardour 5.12.0
Qtractor 0.9.5
Camomile 1.0.7 

3. **Describe the problem or the feature request**
Meta parameters don't trigger any parameter changes UNTIL the GUI has been instantiated at least once.

Behavior the same with or without -meta tag (-meta true).

-LV2 only, the meta controls are functional at start in VST3 plugin.

**Comment by pierreguillot** [comment] 2021-01-15 08:36
Can you share the patch/plugin? And do you have any example of an LV2 plugin that has meta parameters, this way I can see how it should be managed?

**Comment by GModal** [comment] 2021-01-15 22:17
I believe I didn't see this behavior in the beta you provided earlier (with the JUCE dialogs).

**Comment by pierreguillot** [comment] 2021-01-18 08:47
So the problem is fixed?

**Comment by pierreguillot** [comment] 2021-10-31 08:16
I close the issue, feel free to reopen it if the problem persists with the last beta version of v1.0.8.

**Closed as completed by pierreguillot** 2021-10-31 08:16 UTC
Labels: bug, linux, lv2
