### ISSUE TITLE
"midionly" plugins not working as VST3

### ISSUE THREAD

**Issue by anxefaraldo** [pierreguillot/Camomile#238] opened 2021-02-02 23:34 UTC
Hi there,

I am preparing a few didactic MIDI patches/plugins for a class. I used to work with 1.0.6 before, but as I upgraded and tested  v 1.0.7 and 1.0.8 beta, I realised that the behaviour of MIDI plugins differs between the discontinued VST2 and VST3.

In particular, for midi-only plugins I used to write “midionly true;” in the properties file, and the bus/iolayout property set to “0 0”. After some experimentation, I have realised in VST3 plugins the following:

“midionly true;” AND/OR “bus 0 0” caused that MIDI plugins:
- do not initialise values (as specified in the parameters list)
- do not receive nor output any midi data.
- when inserted in an FX chain, they break it (i.e. do not receive nor output any midi data.)

When I set the midionly property to “false” and choose at least 1 chan of audio in/out (seems to be indifferent), the plugin works as expected. This behaviour has been tested in the following systems:

OS: Mac OSX Catalina 10.15.7
DAW: Reaper 6, Ableton Live 10
Plugins: VST3 (1.0.6 VST2 works as desired in v.1.0.6) ???
Audio interface: RME Babyface Pro at 44.1 / 48 KHz.

(i attach a simple fixed velocity plugin for illustration)

Additionally (and perhaps related, but perhaps a limitation of Ableton's track management), creating an audio-in / midi-out plugin seems impossible in Ableton Live, possibly to the differentiation between audio and midi tracks (I wanted to make a simple pitch to midi transcription plugin), but results in an error message inside ableton (I could open a different issue for this, if relevant/useful)

<img width="494" alt="Screenshot 2021-02-02 at 23 27 39" src="https://user-images.githubusercontent.com/6861193/106676419-28a11d00-65b7-11eb-8c16-5b505f40582a.png">

[FIXEDVEL.zip](https://github.com/pierreguillot/Camomile/files/5915028/FIXEDVEL.zip)

**Comment by pierreguillot** [comment] 2021-02-03 08:43
I think this is a duplicate of https://github.com/pierreguillot/Camomile/issues/149#issuecomment-672680330 and https://github.com/pierreguillot/Camomile/issues/231.

**Comment by anxefaraldo** [comment] 2021-02-03 09:01
oooops... really sorry about making a dupe issue... I tried searching the issue list, but obviously I failed in doing it... your reply on #149 is quite clarifying. thanks for that, and sorry for the redundancy!

**Comment by pierreguillot** [comment] 2021-02-03 11:11
No problem ;)

**Closed as completed by pierreguillot** 2021-02-03 11:11 UTC
