### ISSUE TITLE
Duplicating Camomile Plugin causes Crash in Ableton

### ISSUE THREAD

**Issue by yaboypax** [pierreguillot/Camomile#245] opened 2021-02-23 22:54 UTC
Only when working in Ableton, I can't duplicate the plugin itself or the track the plugin is on without the DAW crashing, It doesn't happen in Reaper and I don't understand why

Windows 10
Ableton Live 9
pd 0.51.3
Chamomile 1.0.6

**Comment by pierreguillot** [comment] 2021-02-24 07:35
Please, give further information as explained in the template when you create a new issue, otherwise, it might be difficult to help you... 
- How to reproduce the bug step by step. 
- Does it happen with all the plugins or just specific ones (effects or instruments, specific formats)? 
- Does it happen with examples also? 
- Can you share your patch?
- etc.

By the way, the last stable Camomile version is 1.0.7, and the last Ableton Live version is 11. Did you try to update?

**Comment by yaboypax** [comment] 2021-02-24 13:32
The patch itself has an lfo that starts with a loadbang, I assume that might have something to do with it. When I place my plugin on a track in Ableton everything works fine, but when I try to Ctrl+D Duplicate either the plugin or the track (part of my workflow includes constantly duplicating tracks and deleting the clip content) the entire DAW crashes. 

It doesn't happen with any of the examples, just my patch. Also only in Ableton. In Reaper both the plugin and the track can be duplicated with no crash. I think it is the same with Camomile 1.0.7 and I'm probably not updating Ableton any time soon.

**Comment by pierreguillot** [comment] 2021-02-24 13:45
> The patch itself has an lfo that starts with a loadbang, I assume that might have something to do with it.

An LFO can be implemented in many ways (but I don't understand how you can start an LFO with a loadbang) and I guess there are other objects such as a dac for instance. Can't you share the patch? 

> It doesn't happen with any of the examples, just my patch. 

Perhaps, you're doing something bad in your patch and Reaper is simply more conciliant than Live? The best thing to do would be to share your patch.

> I think it is the same with Camomile 1.0.7

Did you test? Or is it an assumption?

**Comment by yaboypax** [comment] 2021-02-24 17:46
I first wrapped it in 1.0.7 and then went to 1.0.6 and had the same problem, just because I wasn't sure if it had anything to do with the newest update. It is probably more likely, as you said, that it is a problem with my patch with which Reaper is more forgiving than Ableton. I just don't quite understand what. 

![paxdelayimage](https://user-images.githubusercontent.com/79543704/109042190-e347ab00-769d-11eb-8bc1-1412b5f766ab.png)

**Comment by pierreguillot** [comment] 2021-02-25 12:37
Can you put your plugin into a zip file and upload it? I'm test it and try to debug it.

**Comment by yaboypax** [comment] 2021-02-25 13:37
[PaxDelay.zip](https://github.com/pierreguillot/Camomile/files/6043269/PaxDelay.zip)

**Comment by pierreguillot** [comment] 2021-02-26 08:33
I tried on Windows 10 with Ableton Live 9.7.7 and Ableton Live 11 and didn't encounter any issue. In an default new document, I add the plugin to the first track then duplicated the track. When the application crashes, you should receive a crash report, it would be useful to share it. And perhaps the crash depends on the block size, the sample rate, or your hardware. But as I still don't have any of this information, I'm sorry but I can't help you.

**Comment by pierreguillot** [comment] 2021-03-08 08:00
I close this issue due to a lack of information and activity but feel free to reopen it if necessary.

**Closed as completed by pierreguillot** 2021-03-08 08:00 UTC
