### ISSUE TITLE
Can't find the configuration file - Error on Mac

### ISSUE THREAD

**Issue by Totopo27** [pierreguillot/Camomile#81] opened 2018-01-26 05:15 UTC
Hi, I have this problem on my Mac: camomile can't find the configuration file "/Users/Luis/Library/Audio/Plug-Ins/Components/Camomile.component/Contents/Resources/Camomile.txt"

The Plugin appears on Ableton Live and Logic but does not work, it says "Plugin Not Valid"...

**Comment by pierreguillot** [comment] 2018-01-26 10:29
Hi,
Please, read the documentation and especially the parts [How to generate plugins](https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins) and [How to install plugins](https://github.com/pierreguillot/Camomile/wiki/How-to-install-plugins), you'll find the answer. Also, you can also look for answer to your questions in the other issues. If you don't find a solution, or if the answers are still not clear enough, then you more than welcome to open an issue. And please, create a title more explicit than just **error**.  So I close this one because it's not very relevant but feel free to reopen it (and change the name) if you need.

Cheers

**Comment by Totopo27** [comment] 2018-01-26 14:10
<img width="1280" alt="captura de pantalla 2018-01-25 a las 11 00 48 p m" src="https://user-images.githubusercontent.com/35828647/35443184-cd7def5a-026f-11e8-8035-dbe05be9e9b3.png">

**Comment by pierreguillot** [comment] 2018-01-26 14:26
Yes, it's normal if you don't read the documentation so I repeat, please read the documentation and tell me what you don't understand

**Comment by Totopo27** [comment] 2018-01-26 15:01
<img width="1280" alt="captura de pantalla 2018-01-26 a las 9 00 18 a m" src="https://user-images.githubusercontent.com/35828647/35445487-6407f5e0-0277-11e8-8704-0fdf4d3105fd.png">

Thanks for the help, now I have this problem...

**Comment by pierreguillot** [comment] 2018-01-26 15:10
It means that you used **CamomileFx.vst** to create **MiniMock.vst** instead of **Camomile.vst**. **CamomileFx.vst** is the effect version of the plugin, but  **MiniMock** is an instrument so you need to use **Camomile.vst** that is the instrument version of the plugin. See step 3 and 4 of [How to generate plugins](https://github.com/pierreguillot/Camomile/wiki/How-to-generate-plugins), perhaps I should rewrite the sentence, it seems confused.

**Comment by Totopo27** [comment] 2018-01-26 15:13
Ah ok, its an excellent work, but do you have consider to make a vimeo video for the installation processes Windows, Linux, Mac?

**Comment by pierreguillot** [comment] 2018-01-26 15:26
Yes, but I don't have time. It would be great if somebody else help me for that.

**Comment by Totopo27** [comment] 2018-01-26 15:46
Well, if I can fix the problem, maybe I can do it, but in Spanish, because I´m not a good english speaker... Man I still have a problem, now it seems to be ok, but does not sound, look at this: 
<img width="1280" alt="captura de pantalla 2018-01-26 a las 9 45 24 a m" src="https://user-images.githubusercontent.com/35828647/35447567-a91dc10e-027d-11e8-8278-b32db6319b1e.png">

**Comment by Totopo27** [comment] 2018-01-26 15:48
On the other hand, it was impossible to me to install it in Logic as an AU

**Comment by pierreguillot** [comment] 2018-01-26 20:45
> Well, if I can fix the problem, maybe I can do it, but in Spanish, because I'm not a good english speaker...

I can create an issue for this to ask people doing it. Or I'll take time to do it... But if you do a tutorial in Spanish, it's already pretty awesome. In fact if you create video tutorials, you can add the link of your channels in the demo/tutorial section fo the wiki.

> Man I still have a problem, now it seems to be ok, but does not sound, look at this:

If the problem is the amount of **tried Users/...** lines, don't worry it's normal ! The **All**  option activates the verbose option of Pd so it displays a lot of information to help the debugging. But as a user, you should keep the **Normal** option and be worry about the orange and red lines only. If the problem is that you have no sound, perhaps it's because it's a MIDI instrument and you need to feed the plugin with MIDI notes. If the problem persists, let create a issue for this ;)

> On the other hand, it was impossible to me to install it in Logic as an AU

I don't have Logic, I use AU on Reaper and it works pretty well. So let create another issue specific for this and explain me a bit more the problem. Do you see the AU plugins in the plugin list of Logic or not? Where did you install the AU plugins? Did you edit the **Info.plist** in the AU plugin bundle?

**Comment by Totopo27** [comment] 2018-01-26 22:08
1- Ok, thanks for that, I probably do the video.
2- I´m going to try making another plugin, in order to check if everything works.
3- I do all the steps of the "How-to-generate-plugins", I change the CFBundleDisplayName, the CFBundleName and later I change the code and name values.

**Comment by pierreguillot** [comment] 2018-01-27 08:24
3 - Logic is really too expensive for me if it's just for tests and there is no trial version so I can't test it and know how it works...  But can you send me or take a picture of the **Info.plist**? And if you changed the **code** and **name** values that are specific to Audio Unit after a first loading in Logic, perhaps the DAW didn't rescan the plugins. You should clear the cache of the AU manager:
`Logic Pro > Preferences > Audio Units Manager -> 'reset and rescan selection'.` from [here](https://www.macprovideo.com/forum/audio/logic-pro/33454).

**Comment by pierreguillot** [comment] 2018-01-31 12:28
I made a tutorial for MacOS if you want to look at it https://vimeo.com/253586694.

**Closed** 2018-02-05 12:23 UTC
Labels: help wanted, question
