### ISSUE TITLE
Build failing on macOS Catalina

### ISSUE THREAD

**Issue by wyan** [pierreguillot/Camomile#169] opened 2020-02-25 20:53 UTC
**Environment**
macOS Catalina 10.15.3
Xcode 11.3.1 Build version 11C504
cmake 3.16.4 (installed with homebrew)

**Problem**
In the build instructions for macOS
```
cd Camomile
cd Dependencies/LibPdBuild/MacOSX && cmake .. -GXcode && cd ../../..
xcodebuild -workspace Camomile.xcworkspace -scheme Camomile-libpd -configuration Release
```
the second command fails with a missing `pthreads` include fail, and the second fails with several errors related to deprecated `i386` architecture.

**Solution**
This turns out to be the same problem explained in issue #163 so the method explained there worked:
- Remove mention of i386 architecture on line 13 in file `Dependencies/LibPdBuild/CMakeLists.txt`
- Open the Xcode project
- In each of the four components, go to _ComponentName_ > Project > Build Settings > All, and in the Architectures > Valid Architectures field, remove `i386`

**Comment by pierreguillot** [comment] 2020-03-02 13:57
Yes, this is a duplicate of #163.

**Closed by pierreguillot** 2020-03-02 13:57 UTC
