### ISSUE TITLE
presets?

### ISSUE THREAD

**Issue by artofmus** [pierreguillot/Camomile#23] opened 2016-04-09 19:06 UTC
Thank You for awesome project! Plan you add opportunity save/load presets?

**Comment by pierreguillot** [comment] 2016-04-10 07:30
Yes, I think at something. The patch should be able to receive a name and an index of a preset via the symbol "$0-preset" for example. But I'm not really sure how the patch should notify the plugin. The problem is that Camomile can't bind to any symbol before the patch has been loaded. So perhaps, after the loading, the plugin send a bang via a symbol like "$0-getinfos" and when the patch receives the bang, it sends back a list like "presets mypreset1 mypreset2 ..." to notifies the plugin about the available presets.

**Comment by artofmus** [comment] 2016-04-11 05:46
Ok Thanks! Can you show simple example patch for this? I try but no results(

**Comment by pierreguillot** [comment] 2016-04-11 06:15
Sorry, there's a misunderstanding. I'm thinking about it, I didn't made it. I still not sure if this is the good way to do it.

**Comment by pierreguillot** [comment] 2017-11-14 20:52
Will be integrated to the next release #58

**Closed by pierreguillot** 2017-11-14 20:52 UTC
Labels: enhancement
