### ISSUE TITLE
Linux LV2 & VST3: 'Flower' console blocks most parameter changes

### ISSUE THREAD

**Issue by GModal** [pierreguillot/Camomile#201] opened 2020-09-04 15:27 UTC
2. **Describe your environment**
Debian Buster, stable
Carla 2.2.0-RC1
Ardour 5.12.0
Qtractor 0.9.5
Camomile 1.0.7 

3. **Describe the problem or the feature request**
When the 'Flower' window is open, most (but not all) of the parameters are non-functional. 

Being able to observe the timing of errors while accessing the GUI would be nice.

**Comment by pierreguillot** [comment] 2021-01-12 18:18
I tried using Reaper for Linux with Camomile v1.0.8-beta and I didn't have any issue. Then I installed Carla but I couldn't generate any sound to test (I couldn't even play a sound file directly to the output and the connection couldn't be deleted so I gave up). And then I installed Ardour and since then Ubuntu crashes and I can't even restart the system... I'm reinstalling the OS but if you can test it again, it would be great! And if you can try to figure out if the problem doesn't come from the DAWs that you use because if Reaper works fine (please, try it, you can test it for free),  there is a chance that the problem is not the plugin but the DAWs (that seem a bit unstable).

**Comment by GModal** [comment] 2021-01-13 01:37
Sure, I will get a copy of Reaper and test it there.

Current behavior with Carla: I am able to move 1 to 4 of the controls (varied by plugin) with the Flower console open, but the rest are frozen.

With Ardour: the same as Carla. 1 or very few controls move when the console is open.

**Comment by pierreguillot** [comment] 2021-01-13 07:58
So this is still happening with both the LV2 and VST3 versions?

**Comment by GModal** [comment] 2021-01-14 22:44
OK, I've tried this in Reaper (VST3). At first I observed the same behavior (some controls frozen), but with more testing I realize **moving** the flower console window "unfreezes" the controls (generally, sometime they refreeze).

Screenshot of reaper with window first open -- note the "OFFLINE" tag Reaper adds to the sample track:

![reaper1](https://user-images.githubusercontent.com/67518669/104657993-f4110400-568f-11eb-8f72-edb8820007b8.png)

Tried this in Carla (LV2) and it is the same- moving the console window unfreezes the plugin controls.

**Comment by pierreguillot** [comment] 2021-01-15 08:21
I think your problem on Reaper is related to the option(s) "Close audio device when stopped/inactive ...".  I think that Reaper considers the flower window as another application and put the audio offline. You should disable that in the Preferences/Audio. Perhaps is there a similar option on Carla (and Ardour)? Or do you know any plugin that uses floating windows to compare?

**Comment by GModal** [comment] 2021-01-15 22:32
First-- is there a way push debugging messages into the flower console (like a print obj)? Maybe I should open a separate issue..

Carla has some options regarding enabling UI bridges, etc. I've played with those, but always assumed their utility was limited to plugins that _really_ misbehave.

**Regarding Reaper & flower console/controls**

--Reaper option: Preferences->Audio->

"Close audio device when stopped and application is inactive" is not checked. 
- Enabling doesn't change behavior.

"Close audio device when inactive and ReWire devices are open" is not checked. 
- Enabling doesn't change behavior.

"Close audio device when stopped and active (less responsive)" is not checked. 
- Enabling doesn't change behavior.

In a side note, my personal preferences for audio port management (in Linux w/JACK) is for any application to NOT alter the current connections once they are established. Those that do (Audacity, for instance) make that app impractical to use with other processing chains in JACK (like routing through other apps & plugin hosts in realtime). I know this is a JACK-centric attitude, and folks who do all their processing INSIDE the DAW don't share this way of thinking.

Tried this option in Reaper as well:
-- option:Preferences->VST->
"Inform plugins of offline rendering state" 
- Either option doesn't change behavior.

**Comment by GModal** [comment] 2021-01-16 17:06
Scratch that first question. I see the print obj does work with the Flower console, now that I can work around the "freeze."

**Comment by pierreguillot** [comment] 2021-01-22 11:25
I tested and I don't have any issue:

 - Ubuntu 20.04.1 LTS - 64bit
  - Ardour 6.5.0 & Carla 2.2.0
  - PdStal & Bulgroz plugins example and Camomile v1.0.8 beta4

On Ardour, the 2 plugins are loaded on a track, I open the GUI and the Console Window of both plugins, I start the playback and modify the parameters using the DAW interface and the plugin interface and it seems responsive.

On Carla, the 2 plugins are loaded into the rack, I open the GUI and the Console Window of one plugin, I modify the parameters using the DAW interface and the plugin interface and it seems responsive.

Can you test it and confirm?

By the way, the offline mode on Reaper, should be only active with "Close audio device when stopped and application is inactive"  is enabled but as the Linux Reaper version is still "unstable", perhaps this is not working yet.

**Comment by pierreguillot** [comment] 2021-10-30 14:33
I updated Juce and changed the way the dropdown menu is handled, can you try these binaries and tell me if it's okay now? Thank you. 

https://github.com/pierreguillot/Camomile/actions/runs/1402491699

**Comment by GModal** [comment] 2021-10-31 14:07
> I updated Juce and changed the way the dropdown menu is handled, can you try these binaries and tell me if it's okay now? Thank you.
> 
> https://github.com/pierreguillot/Camomile/actions/runs/1402491699

I'd be glad to, Pierre, but this link points to logs, not the binaries.

**Comment by jocphx** [comment] 2021-10-31 14:30
Just scroll to the bottom of the page

**Comment by GModal** [comment] 2021-10-31 18:04
> Just scroll to the bottom of the page

Oops. Thanks!

**Comment by GModal** [comment] 2021-11-02 00:41
I'm having numerous problems with this binary -- but the console blocking behavior isn't one. That now seems to work smoothly.

Bulgroz and Castafiore cause segmentation errors when invoking ./camomile:
```
Bulgroz:
Saving preset 2/4..../camomile: line 243: 16995 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$PWD "$ThisPath/lv2_file_generator" "$plugin_output_dir/$plugin_name.lv2/$plugin_name.$LinuxLV2Extension" $plugin_name
Castafiore:
Saving preset 2/4..../camomile: line 243: 16995 Segmentation fault      (core dumped) LD_LIBRARY_PATH=$PWD "$ThisPath/lv2_file_generator" "$plugin_output_dir/$plugin_name.lv2/$plugin_name.$LinuxLV2Extension" $plugin_name
```
Not seeing those errors with my plugins I tested, but other problems exist:
 - Generally the beta plugins crash Carla when a second (beta) plugin is loaded. Lv2 or vst3; it happens with both. These plugins were generated without errors.
 - One of the more complex plugins has a much increased DSP load (8-9% with a previous beta version; 22-24% with this beta). This plugin uses oversampling (but I don't think 0.51.4 has changed [inlet~ pad]).

To be honest, I haven't been able to use any precompiled Camomile versions for some time (always have a segfault), and work from a version I compiled locally, from one of the beta tags (1.0.8 beta4?). This may have something to do with using KXStudio repositories. The fact that I CAN use this precompiled binary semi-successfully is encouraging, somewhat.

So my setup might not reflect a typical 20.04 install. Still -- I use Synaptic fairly often to install binaries, and compile code often, and don't seem to have any issues...

I know this doesn't help much.

**Comment by pierreguillot** [comment] 2021-11-02 08:27
Hi, Thank you!

> ... but the console blocking behavior isn't one. That now seems to work smoothly.

Okay, great! So I can close this issue.

> Bulgroz and Castafiore cause segmentation errors when invoking ./camomile:

Okay, I will investigate.

For the other problems, can you create a specific issue for each of them with details and relevant information to reproduce?

**Closed as completed by pierreguillot** 2021-11-02 08:27 UTC
Labels: bug, linux, lv2

**Comment by GModal** [comment] 2021-11-03 20:06
> Hi, Thank you!
> 
> > ... but the console blocking behavior isn't one. That now seems to work smoothly.
> 
> Okay, great! So I can close this issue.
> 
> > Bulgroz and Castafiore cause segmentation errors when invoking ./camomile:
> 
> Okay, I will investigate.
> 
> For the other problems, can you create a specific issue for each of them with details and relevant information to reproduce?

Yes, I'll try to run down repeatable (bad) behavior and create new issue posts.
